#!bin/sh

dot=.
function print_result(){
  diff mine real | cat -e > dif
  if [ -s dif ]
  then
    echo "TEST $1      FAIL - $2 with option -$3"
    else
    echo "TEST $1      OK"
  fi
}

options=(1 l R a r)

# TEST 1___________________

test_desc=List_all_files
test_nbr=1
count=0
for option in ${options[@]}
do
  :
  float=$test_nbr$dot$count
  ((count++))
  mkdir tests && cd tests && touch 1 3 2 4 a b d c e .hide_me && cd ..
  ./ft_ls -$option tests | cat > mine
  ls -1$option tests | cat > real
  print_result $float $test_desc $option
  rm -rf tests dif real mine
done
echo ""

# TEST 2____________________

test_desc=List_all_directories
test_nbr=2
count=0
for option in ${options[@]}
do
  :
  float=$test_nbr$dot$count
  ((count++))
  mkdir tests && cd tests && mkdir 1 3 2 4 a d c e .hide_me && cd ..
  ./ft_ls -$option tests | cat > mine
  ls -1$option tests | cat > real
  print_result $float $test_desc $option
  rm -rf tests dif real mine
done
echo ""

# TEST 3____________________

test_desc=List_files_and_directories
test_nbr=3
count=0
for option in ${options[@]}
do
  :
  float=$test_nbr$dot$count
  ((count++))
  mkdir tests && cd tests && mkdir 1 3 2 4 a d c e .hide_me && touch bibi baba bobo && cd ..
  ./ft_ls -$option tests | cat > mine
  ls -1$option tests | cat > real
  print_result $float $test_desc $option
  rm -rf tests dif real mine
done
echo ""

# TEST 4____________________

test_desc=Dirs_inside_dirs
test_nbr=4
count=0
for option in ${options[@]}
do
  :
  float=$test_nbr$dot$count
  ((count++))
  mkdir tests && cd tests && mkdir 1 2 3 4 5 && mkdir 1/11 2/22 3/33 && touch 1/11/111 2/22/222 3/33/333 && cd ..
  ./ft_ls -$option tests | cat > mine
  ls -1$option tests | cat > real
  print_result $float $test_desc $option
  rm -rf mine real dif tests
done
echo ""
